---
title: "Trump Falsehood Breakdown Report"
output:
  html_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(googlesheets)
library(kableExtra)
library(leaflet)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
options(tigris_class = "sf")
library(DT)
library(kableExtra)
library(readxl)


raw_data <- read_excel("TRUMP FACT-CHECKS.xlsx", 
                                sheet = "ak", col_types = c("date", "text", 
                                                            "text", "text", "text", "text", "text", 
                                                            "text", "text", "text", "numeric", 
                                                            "text"))


glimpse(raw_data)

#clean column names
fcheck <- raw_data %>% 
  clean_names() 

names(fcheck)

#set formatting of certain columns and break out dates into own columns
fcheck <- fcheck %>% 
  mutate(
    kind_of_forum = str_trim(str_to_upper(kind_of_forum)),
    location = str_trim(str_to_upper(location)),
    category_tag1 = str_trim(str_to_upper(category_tag1)),
    category_tag2 = str_trim(str_to_upper(category_tag2)),
    category_tag3 = str_trim(str_to_upper(category_tag3)),
    category_tag4 = str_trim(str_to_upper(category_tag4)),
    year = year(date),
    month = month(date),
    day = day(date),
    week = week(date)
  )

fcheck <- fcheck %>% 
  mutate(
    kind_of_forum = as.factor(kind_of_forum),
    location = as.factor(location)
  )

# remove NAs from link column 
fcheck$source_article <- fcheck$source_article %>% replace_na("")

#convert link to html hyperlink format
fcheck$source_article <- paste0("<a href='", fcheck$source_article, "' target='_blank'>", fcheck$source_article, "</a>")

#create table of JUST THE PREVIOUS WEEK's checks
fcheck_PREVWEEK <- fcheck %>%
  filter(date <= today("EST"),
         date >= today("EST")-7)

### count up subject categories stretching across four data columns #### --------------------
tag1 <- fcheck %>% 
  select(tag = category_tag1)

tag2 <- fcheck %>% 
  select(tag = category_tag2)

tag3 <- fcheck %>% 
  select(tag = category_tag3)

tag4 <- fcheck %>% 
  select(tag = category_tag4)

#combine into one
tag_combined <- bind_rows(tag1, tag2, tag3, tag4)

#filter out NAs
tag_combined <- tag_combined %>% 
  filter(!is.na(tag))

category_tag_count <- tag_combined %>% 
  count(tag) %>% 
  arrange(desc(n))


### Now the same for PREV WEEK ONLY
tag1b <- fcheck_PREVWEEK %>% 
  select(tag = category_tag1)

tag2b <- fcheck_PREVWEEK %>% 
  select(tag = category_tag2)

tag3b <- fcheck_PREVWEEK %>% 
  select(tag = category_tag3)

tag4b <- fcheck_PREVWEEK %>% 
  select(tag = category_tag4)

#combine into one
tag_combined <- bind_rows(tag1b, tag2b, tag3b, tag4b)

#filter out NAs
tag_combined_PREVWEEK <- tag_combined %>% 
  filter(!is.na(tag))

category_tag_PREVWEEK_count <- tag_combined_PREVWEEK %>% 
  count(tag) %>% 
  arrange(desc(n))


# #subject count - all
# subject_count <- category_tag_count %>% 
#   nrow()
# 
# #subject count - previous week only
# subject_count_PREVWEEK <- category_tag_PREVWEEK_count %>% 
#   nrow()

 
# set time object set to eastern time
d <- Sys.Date()
# d <- .POSIXct(d, "EST")
  
t <- Sys.time()
t <- .POSIXct(t, "EST")

```


The latest full spreadsheet with all the raw entries can be downloaded [HERE](https://www.cnn.com)

Summary breakdowns below as of `r format(Sys.time(), "%a %b %d %X")`



Topline Totals To Date

<!-- Total Trump false claims: `r nrow(fcheck)` -->

<!-- Number of forum types: `r fcheck %>% count(kind_of_forum) %>% pull()` -->

<!-- Top forum type: `r fcheck %>% count(kind_of_forum) %>% arrange(desc(n)) %>% head(1) %>% select(kind_of_forum) %>% pull() %>% str_to_title()` -->

<!-- Top individual forum: `r fcheck %>% count(forum) %>% arrange(desc(n)) %>% head(1) %>% select(kind_of_forum) %>% pull() %>% str_to_title()` -->

<!-- Top Subject Categories -->

```{r echo=FALSE}

category_tag_count %>%
    head() %>%
    kable() %>%
    kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = F,
                position = "left")

```

